version: "3.9"
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './:/var/www/project'

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - './:/var/www/project'

  mysql:
    build:
      context: ./docker/mysql
    platform: linux/x86_64
    volumes:
      - './mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
